### ISSUE TITLE
Session: Showcase is broken

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1124]
See: https://www.primefaces.org/showcase-ext/sections/session/basic.jsf

```
Message: Could not initialize class org.primefaces.extensions.component.session.SessionRenderer
Timestamp: 2023-03-28 18:33:15
StackTrace: java.lang.NoClassDefFoundError: Could not initialize class org.primefaces.extensions.component.session.SessionRenderer
at sun.reflect.GeneratedConstructorAccessor4288.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at org.apache.myfaces.shared.util.ClassUtils.newInstance(ClassUtils.java:426)
at org.apache.myfaces.renderkit.html.HtmlRenderKitImpl$LazyRendererWrapper.getWrapped(HtmlRenderKitImpl.java:460)
at org.apache.myfaces.renderkit.html.HtmlRenderKitImpl.getRenderer(HtmlRenderKitImpl.java:133)
at org.apache.myfaces.application.ApplicationImpl._inspectRenderer(ApplicationImpl.java:2631)
at org.apache.myfaces.application.ApplicationImpl.createComponent(ApplicationImpl.java:1478)
at javax.faces.application.ApplicationWrapper.createComponent(ApplicationWrapper.java:133)
at javax.faces.application.ApplicationWrapper.createComponent(ApplicationWrapper.java:133)
at org.apache.myfaces.view.facelets.tag.jsf.ComponentTagHandlerDelegate.createComponent(ComponentTagHandlerDelegate.java:604)
at org.apache.myfaces.view.facelets.tag.jsf.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:284)
at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:51)
at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:46)
at org.apache.myfaces.view.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:160)
at org.apache.myfaces.view.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:66)
at org.apache.myfaces.view.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:48)
at org.apache.myfaces.view.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:519)
at org.apache.myfaces.view.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:573)
at org.apache.myfaces.view.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:551)
at org.apache.myfaces.view.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:240)
at org.apache.myfaces.view.facelets.tag.ui.IncludeHandler.apply(IncludeHandler.java:229)
```

**Comment by melloware** [comment]
cc @fcorneli

**Comment by fcorneli** [comment]
@melloware Will have a look at it.

**Comment by fcorneli** [comment]
Running the showcase here works as expected.
Is the runtime used by https://www.primefaces.org/showcase-ext/ the same as the runtime when you do:
```
cd showcase
mvn clean jetty:run
```
?

**Comment by fcorneli** [comment]
PS: we're already using the `pe:session` component in multiple projects here, no issues reported so far.

**Comment by melloware** [comment]
Ahhh i wonder if its a MyFaces 2.3 thing as that is how it runs on PrimeTek site?

**Comment by melloware** [comment]
Yep its working for me locally too and deployed to Jetty the same as PrimeTek.  So maybe its something else?

**Comment by melloware** [comment]
It might actually be this issue: https://github.com/primefaces-extensions/primefaces-extensions/issues/1111

**Comment by fcorneli** [comment]
Yeah... was thinking the same.
