### ISSUE TITLE
Sheet: Dropdown for filtering columns is buggy when clicked after clicking a cell

### ISSUE THREAD

**Issue by SosaXIII** [primefaces-extensions/primefaces-extensions#1560]
### Describe the bug

If i first click a cell in the table and then click on a filter dropdown, the dropdown will disappear immediately. Clicking it repeatedly will make it display correctly (sometimes 2 clicks, cometimes 3 clicks).

Somehow holding the mouse button would work on the first click, but i dont think this is intentional.

Tested this with 3 different PCs (Win 10 and Win 11) with Firefox and Edge Chromium. It also happens with the Sheet Demo.

### Reproducer

1. Open the Demo
2. Click on a random cell
3. Try to open a filter dropdown in a column header (In the demo its either "Type", "Platform" or "Arch" column)

### Expected behavior

I expected the dropdown to display correctly on the first click.

### PrimeFaces Extensions version

14.0.0

### JSF implementation

MyFaces

### JSF version

2.3

### Browser(s)

Edge Version 125.0.2535.67 (Official Build) (64-Bit), Firefox 115.10.0esr (64-Bit)

**Comment by melloware** [comment]
Agreed, i see it.  You can probably investigate what is going on in `1-sheet.js` with the click events

**Comment by SosaXIII** [comment]
@melloware i would love to help but sadly my skills are pretty rudimentary. I looked into the 1-sheet.js but it wasnt obvious to me what might be going wrong there.

**Comment by melloware** [comment]
Ok I will take a look

**Comment by andreas-wagner-dev** [comment]
Hello together @melloware, @SosaXIII,  

maybe this can be fixed in the class org.primefaces.extensions.component.sheetSheetRenderer.java
Because i runnig in the same problem and i fixed it in this way:

**My Error logs**

05:08:41,845 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-63) JSONArray[2] is not a int (class org.primefaces.shaded.json.JSONObject$Null : null).: org.primefaces.shaded.json.JSONException: JSONArray[2] is not a int (class org.primefaces.shaded.json.JSONObject$Null : null).
	at deployment.group-problem-exchange.war//org.primefaces.shaded.json.JSONArray.wrongValueFormatException(JSONArray.java:2037)
	at deployment.group-problem-exchange.war//org.primefaces.shaded.json.JSONArray.getInt(JSONArray.java:514)
	at deployment.group-problem-exchange.war//org.primefaces.extensions.component.sheet.SheetRenderer.updateSheetSelection(SheetRenderer.java:897)
	at deployment.group-problem-exchange.war//org.primefaces.extensions.component.sheet.SheetRenderer.decodeSelection(SheetRenderer.java:878)
	at deployment.group-problem-exchange.war//org.primefaces.extensions.component.sheet.SheetRenderer.decode(SheetRenderer.java:776)

**Error Analysis**

some of the value of the array can be or is null e.g. [0,51,null,51] 
the access of array.getInt(2) is illegal and can not be cast to the target type of integer

```
    private void updateSheetSelection(final Sheet sheet, final JSONArray array) throws JSONException {
        **// data comes in: [ [row, col, oldValue, newValue] ... ]**
        sheet.setSelectedRow(array.getInt(0));
        sheet.setSelectedColumn(sheet.getMappedColumn(array.getInt(1)));
        sheet.setSelectedLastRow(array.getInt(2)); // <--- 
        sheet.setSelectedLastColumn(array.getInt(3));
    }
```

**Workaround (by classloader overloading with own SheetRenderer class)**:

1. Copy org/primefaces/extensions/component/sheet/SheetRenderer.java exactly  under src/main/java/org/primefaces/extensions/component/sheet/SheetRenderer.java in your project.

2. extends your 
```

<faces-config ....>

	<render-kit>
		<render-kit-id>HTML_BASIC</render-kit-id>
		<renderer>
			<component-family>org.primefaces.extensions.component</component-family>
			<renderer-type>org.primefaces.extensions.component.sheet.SheetRenderer</renderer-type>
			<renderer-class>org.primefaces.extensions.component.sheet.SheetRenderer</renderer-class>
		</renderer>

	</render-kit>

	<ordering>
		<after>
			<name>primefaces_extensions</name>
		</after>
	</ordering>
	
</faces-config>

```
3. Fix affected methods of the SheetRenderer.java **in your classpath**.

`````
	private void updateSheetSelection(final Sheet sheet, final JSONArray array) throws JSONException {
		**// safe access for possibly null values**
		sheet.setSelectedRow(array.optInt(0, -1));
		sheet.setSelectedColumn(sheet.getMappedColumn(array.optInt(1, -1)));
                **// safe access or default values of index of  first row or column**
		sheet.setSelectedLastRow(array.optInt(2, sheet.getSelectedRow()));
		sheet.setSelectedLastColumn(array.optInt(3, sheet.getSelectedColumn()));
	} 
```

	//  **FIX for jakarta namespace**, otherwise no ajax events would be fired 

```
	protected void decodeBehaviors(final FacesContext context, final UIComponent component) {
		// get current behaviors
		final Map<String, List<ClientBehavior>> behaviors = ((ClientBehaviorHolder) component).getClientBehaviors();
		// if empty, done
		if (behaviors.isEmpty()) {
			return;
		}

		// get the parameter map and the behaviorEvent fired
		final Map<String, String> params = context.getExternalContext().getRequestParameterMap();
		**//  TODO: FIX for jakarta namespace**
		final String behaviorEvent = params.getOrDefault("javax.faces.behavior.event",
				params.get("jakarta.faces.behavior.event"));

		// if no event, done
		if (behaviorEvent == null) {
			return;
		}

		// get behaviors for the event
		final List<ClientBehavior> behaviorsForEvent = behaviors.get(behaviorEvent);
		if (behaviorsForEvent == null || behaviorsForEvent.isEmpty()) {
			return;
		}
	
		// decode event if we are the source
	       **//  TODO: FIX for jakarta namespace**
		final String behaviorSource = params.getOrDefault("javax.faces.source", params.get("jakarta.faces.source"));
		final String clientId = component.getClientId();
		if (clientId.equals(behaviorSource)) {
			for (final ClientBehavior behavior : behaviorsForEvent) {
				behavior.decode(context, component);
			}
		}
	}
```

I hope this helps or maybe it is a new Issue?

**Comment by melloware** [comment]
@andreas-wagner-dev please submit a PR with your fix!
