### ISSUE TITLE
CombinedResourceHandler: MyFaces ParseError in Dev Mode

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#517]
**Describe the bug**
@tandraschko I have attached this reproducer:
[pfe-combinedresourcehandler.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/7059882/pfe-combinedresourcehandler.zip)

To get the issue run the reproducer `mvn clean jetty:run -Pmyfaces23` with JSF mode **Development** and press the "Update" button twice.  On the second press you will see this in the console for the AJAX response.
![image](https://user-images.githubusercontent.com/4399574/130966870-0e43e56a-3fe5-4351-8c4a-e3754fa2e265.png)

Now run the reproducer again in JSF mode **Production**  `mvn clean jetty:run -Pmyfaces23` and there is no errors or problems.  I think it stems from MyFaces having an issue with duplicate ID's for this piece of code in our handler:
https://github.com/primefaces-extensions/primefaces-extensions/blob/fd939e77a2e26c765bd06efa5692fde8e3fba4b2/core/src/main/java/org/primefaces/extensions/application/PrimeFacesScriptProcessor.java#L169-L175

I used to have ID's on there but had to be removed because of this ticket: https://github.com/primefaces-extensions/primefaces-extensions/issues/486

Any thoughts you have on this would be appreciated.  It works fine in Mojarra in Development mode but I am wondering which library is doing the right thing?

**Comment by tandraschko** [comment]
no exception, stracktrace and so on?

**Comment by melloware** [comment]
This is what I have in the console...

```

INFO: MyFaces Core Servlet 4.0 support disabled
Aug 26, 2021 8:55:18 AM javax.faces.validator.BeanValidator validate
WARNING: cannot validate component with empty value: frmTest:j_id_a
Aug 26, 2021 8:55:18 AM javax.faces.validator.BeanValidator validate
WARNING: cannot validate component with empty value: frmTest:default
Aug 26, 2021 8:55:26 AM javax.faces.validator.BeanValidator validate
WARNING: cannot validate component with empty value: frmTest:j_id_a
Aug 26, 2021 8:55:26 AM javax.faces.validator.BeanValidator validate
WARNING: cannot validate component with empty value: frmTest:default
Aug 26, 2021 8:55:26 AM org.apache.myfaces.context.servlet.ServletExternalContextImpl setResponseContentType
SEVERE: Cannot set content type. Response already committed
```

**Comment by melloware** [comment]
When I run PFE showcase locally with `mvn clean jetty:run` and go to the TimePicker example and press the Submit button twice I get this stack trace from Myfaces.

```
org.apache.myfaces.view.facelets.compiler.DuplicateIdException: Component with duplicate id "j_id__v_7" found. The first component is {Component-Path : [Class: javax.faces.component.UIViewRoot,ViewId: /sections/timePicker/basicUsage.xhtml][Class: org.apache.myfaces.component.ComponentResourceContainer,Id: javax_faces_location_head][Class: javax.faces.component.UIOutput,Id: j_id__v_7]}
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.createAndQueueException(CheckDuplicateIdFaceletUtils.java:148)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:105)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:120)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:120)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:114)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:87)
        at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.saveView(DefaultFaceletsStateManagementStrategy.java:724)
        at org.apache.myfaces.application.StateManagerImpl.saveView(StateManagerImpl.java:213)
        at javax.faces.application.StateManager.getViewState(StateManager.java:263)
        at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:557)
        at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:420)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:97)
        at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:571)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:542)
        at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1897)
        at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
        at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:155)
        at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:122)
        at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:266)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:206)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
        at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:123)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:834)
Aug 26, 2021 9:10:22 AM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
SEVERE: Component with duplicate id "j_id__v_7" found. The first component is {Component-Path : [Class: javax.faces.component.UIViewRoot,ViewId: /sections/timePicker/basicUsage.xhtml][Class: org.apache.myfaces.component.ComponentResourceContainer,Id: javax_faces_location_head][Class: javax.faces.component.UIOutput,Id: j_id__v_7]}
org.apache.myfaces.view.facelets.compiler.DuplicateIdException: Component with duplicate id "j_id__v_7" found. The first component is {Component-Path : [Class: javax.faces.component.UIViewRoot,ViewId: /sections/timePicker/basicUsage.xhtml][Class: org.apache.myfaces.component.ComponentResourceContainer,Id: javax_faces_location_head][Class: javax.faces.component.UIOutput,Id: j_id__v_7]}
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.createAndQueueException(CheckDuplicateIdFaceletUtils.java:148)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:105)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:120)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:120)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:114)
        at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:87)
        at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.saveView(DefaultFaceletsStateManagementStrategy.java:724)
        at org.apache.myfaces.application.StateManagerImpl.saveView(StateManagerImpl.java:213)
        at javax.faces.application.StateManager.getViewState(StateManager.java:263)
        at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:557)
        at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:420)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:97)
        at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:571)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:542)
        at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1897)
        at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
        at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:155)
        at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:122)
        at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:266)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:206)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
        at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:123)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:834)

Aug 26, 2021 9:10:22 AM org.apache.myfaces.context.servlet.ServletExternalContextImpl setResponseContentType
SEVERE: Cannot set content type. Response already committed

```

**Comment by tandraschko** [comment]
ok
DuplicateIDCheck is not active in production for performance reason

**Comment by melloware** [comment]
Yep that makes sense so it works. is there a way to disable it in Development mode as well?

**Comment by tandraschko** [comment]
i dont think so

can you try to remove the "content" panel from js? will the same error be thrown?

**Comment by tandraschko** [comment]
when you check MF UIViewRoot#addComponentResource, we only generate a unique for that component, not for childs
that might be the problem

if yes -> a unittest in MF would be great + fix

**Comment by melloware** [comment]
Ahhh yep that might be the issue. Let me look into it.

**Comment by melloware** [comment]
Before when I was manually setting an ID both Mojarra and Myfaces turn it into a SPAN like..

```xml
<script type="text/javascript"><span id="js-12345">if(window.PrimeFaces)...</span></script>
```

So I had to remove the ID's from this to let it generate the script properly without the SPAN

```xml
<script type="text/javascript">if(window.PrimeFaces)...</script>
```

**Comment by melloware** [comment]
OK @tandraschko here is what I have discovered in my research and settled on because I don't know exactly what is wrong in MyFaces or MAY NOT BE WRONG it could be wrong in Mojarra who knows. But...

1. We know Mojarra does not want an ID set on the JS when calling `UIViewRoot.addComponentResource` as reported in this ticket: https://github.com/primefaces-extensions/primefaces-extensions/issues/486
2. MyFaces however if no ID is set automatically adds one because of this ticket:  https://issues.apache.org/jira/browse/MYFACES-2775
3. MyFaces generates the "V" kind of ID like "j_id__v_7" because this is a Script resource and from looking at the code i think its doing it correctly however its reporting DuplicateId when it should be replacing the old "j_id__v_7" because it should be finding that component with the same name.

The solution I settled on was to set an ID for MyFaces and leave it blank for Mojarra.  I have tested and this now works for all 4 use cases MyFaces and Mojarra and Development mode and Production Mode.  

```java
private void addJS(final FacesContext context, final String script) {
        final UIOutput js = new UIOutput();
        js.setRendererType("javax.faces.resource.Script");
        // https://github.com/primefaces-extensions/primefaces-extensions/issues/486
        // https://github.com/primefaces-extensions/primefaces-extensions/issues/517
        // MyFaces needs ID set to prevent duplicate ID check in Dev mode, Mojarra does not
        final PrimeEnvironment environment = PrimeApplicationContext.getCurrentInstance(context).getEnvironment();
        if (!environment.isMojarra()) {
            js.setId("primfaces-script-processor");
        }
        final UIOutput content = new UIOutput();
        content.setValue(script);
        js.getChildren().add(content);
        context.getViewRoot().addComponentResource(context, js);
    }
```

cc @Phipsee since you reported the issues with Mojarra I wanted  you to see this ticket.

**Comment by melloware** [comment]
OK looks like its related to: https://issues.apache.org/jira/browse/MYFACES-4623

**Comment by volosied** [comment]
Hmm. This is a snippet of the generated tree (with CHECK_ID_PRODUCTION_MODE as false in Prod mode). As we can see, UIOutput is nested:

```
  <ComponentResourceContainer id="javax_faces_location_head" facetName="head" clientBehaviors="{}" clientId="javax_faces_location_head" defaultEventName="NULL" eventNames="NULL" facetCount="0" family="javax.faces.Panel" inView="true" namingContainer="NULL" passThroughAttributes="javax.faces.component._PassThroughAttributesMap@0" rendered="true" rendererType="NULL" rendersChildren="false" resourceBundleMap="{}" transient="false" transientStateHelper="javax.faces.component._DeltaStateHelper@4e264e7c">
    <UIOutput id="j_id__v_7" clientBehaviors="{}" clientId="j_id__v_7" converter="NULL" defaultEventName="NULL" eventNames="NULL" facetCount="0" family="javax.faces.Output" inView="true" localValue="NULL" namingContainer="NULL" passThroughAttributes="javax.faces.component._PassThroughAttributesMap@0" rendered="true" rendererType="javax.faces.resource.Script" rendersChildren="true" resourceBundleMap="{}" transient="false" transientStateHelper="javax.faces.component._DeltaStateHelper@5fac2c46">
      <UIOutput id="j_id__v_7" clientBehaviors="{}" clientId="j_id__v_7" converter="NULL" defaultEventName="NULL" eventNames="NULL" facetCount="0" family="javax.faces.Output" inView="true" localValue="if(window.PrimeFaces){PrimeFaces.settings.locale='en_US';PrimeFaces.settings.viewId='/test.xhtml';PrimeFaces.settings.contextPath='/primefaces-test-2.0';PrimeFaces.settings.cookiesSecure=false;}" namingContainer="NULL" passThroughAttributes="javax.faces.component._PassThroughAttributesMap@0" rendered="true" rendererType="javax.faces.Text" rendersChildren="false" resourceBundleMap="{}" transient="false" transientStateHelper="javax.faces.component._DeltaStateHelper@7c555370"/>
    </UIOutput>
  </ComponentResourceContainer>
  ```
  
  This looks to match the logic in the addJS method: 
  
```
        final UIOutput js = new UIOutput();
        js.setRendererType("javax.faces.resource.Script");
        final UIOutput content = new UIOutput();
        content.setValue(script);
        js.getChildren().add(content);
        context.getViewRoot().addComponentResource(context, js);
```

MyFaces just needs to realize it should update the id within the nested element / not add it at all  in order to avoid the duplicate id exception.

**Comment by melloware** [comment]
@volosied awesome!  Yeah this was has been bothering me for a while and I have not been able to chase it down.

**Comment by volosied** [comment]
Was pulled away, but I'm trying to work on this again. One thing I see is the script is added twice, which shouldn't happen I think?

First Add:

```
PrimeFacesScriptProcessor.addJS(FacesContext, String) line: 170	
PrimeFacesScriptProcessor.processEvent(SystemEvent) line: 79	
PostAddToViewEvent(SystemEvent).processListener(FacesListener) line: 49	
PostAddToViewEvent(ComponentSystemEvent).processListener(FacesListener) line: 57	
_ApplicationUtils._traverseListenerList(FacesContext, List<SystemEventListener>, Class<SystemEvent>, Object, SystemEvent) line: 121	
ApplicationImpl$SystemListenerEntry.publish(FacesContext, Class<SystemEvent>, Class<?>, Object, SystemEvent) line: 2737	
ApplicationImpl.publishEvent(FacesContext, Class<SystemEvent>, Class<?>, Object) line: 634	
ApplicationImpl.publishEvent(FacesContext, Class<SystemEvent>, Object) line: 649	
WASApplicationImpl(ApplicationWrapper).publishEvent(FacesContext, Class<SystemEvent>, Object) line: 352	
OmniApplication(ApplicationWrapper).publishEvent(FacesContext, Class<SystemEvent>, Object) line: 352	
RestoreViewExecutor.execute(FacesContext) line: 319	
```

Second Add: 

```
PrimeFacesScriptProcessor.addJS(FacesContext, String) line: 170	
PrimeFacesScriptProcessor.processEvent(SystemEvent) line: 79	
PostAddToViewEvent(SystemEvent).processListener(FacesListener) line: 49	
PostAddToViewEvent(ComponentSystemEvent).processListener(FacesListener) line: 57	
_ApplicationUtils._traverseListenerList(FacesContext, List<SystemEventListener>, Class<SystemEvent>, Object, SystemEvent) line: 121	
ApplicationImpl$SystemListenerEntry.publish(FacesContext, Class<SystemEvent>, Class<?>, Object, SystemEvent) line: 2737	
ApplicationImpl.publishEvent(FacesContext, Class<SystemEvent>, Class<?>, Object) line: 634	
WASApplicationImpl(ApplicationWrapper).publishEvent(FacesContext, Class<SystemEvent>, Class<?>, Object) line: 346	
OmniApplication(ApplicationWrapper).publishEvent(FacesContext, Class<SystemEvent>, Class<?>, Object) line: 346	
FaceletViewDeclarationLanguage.buildView(FacesContext, UIViewRoot) line: 518	
RenderResponseExecutor.execute(FacesContext) line: 84	
LifecycleImpl.render(FacesContext) line: 266	
```


```
<head>
   <title>PrimeFaces Test</title>
   <script type="text/javascript">if(window.PrimeFaces){PrimeFaces.settings.locale='en_US';PrimeFaces.settings.viewId='/test.xhtml';PrimeFaces.settings.contextPath='/primefaces-test-2.0';PrimeFaces.settings.cookiesSecure=false;PrimeFaces.settings.projectStage='Development';}</script>
    ...
    <script type="text/javascript">if(window.PrimeFaces){PrimeFaces.settings.locale='en_US';PrimeFaces.settings.viewId='/test.xhtml';PrimeFaces.settings.contextPath='/primefaces-test-2.0';PrimeFaces.settings.cookiesSecure=false;PrimeFaces.settings.projectStage='Development';}</script>
</head>
```

**Comment by melloware** [comment]
It should definitely not be added twice!

**Comment by melloware** [comment]
I think that is why I tried to add the ID so it would be removed and replaced.

**Comment by volosied** [comment]
Created an issue for the duplicate scripts above.

As for the original issue here...  
I saw we had a id counter and it starts at 0 before the state is stored.  So when the script is added, it's always using the same counter. [ See here.](https://github.com/apache/myfaces/blob/304099d4588383424df9105d5a751911c1c5301a/api/src/main/java/jakarta/faces/component/UIViewRoot.java#L493-L495) 

I think the main issue is that we aren't adding ids to the nested items here: https://github.com/apache/myfaces/blob/304099d4588383424df9105d5a751911c1c5301a/api/src/main/java/jakarta/faces/component/UIViewRoot.java#L218-L224 

We'd need something like: 
```

        if (componentId == null)
        {
            // componentResource can have no id - calling createUniqueId makes us sure that component will have one
            // https://issues.apache.org/jira/browse/MYFACES-2775
            componentId = createUniqueId(context, null);
            componentResource.setId(componentId);
            List<UIComponent> children = componentResource.getChildren();
            for(UIComponent child : children){
                String childId =  createUniqueId(context, null);
                child.setId(childId);
            }
        }
```

Only issue I see above is that I search only the children and don't drill down any further.  Otherwise, it seems to fix the duplicate id exception :)

**Comment by volosied** [comment]
I also removed the `PostAddToViewEvent`  publish event in the restore view phase to avoid the duplicate scripts. However,  I see duplicate scripts  (css) added when i click update in the test app: 

see here: 
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/5934310/e041d3cb-e8f3-4ca7-b5aa-e48047064060)

**Comment by melloware** [comment]
Thanks for tracking this down @volosied I just read Leo's ticket from 2010 and I its seems like it was a very corner and extreme use case he was trying to solve with the PostAddToViewEvent twice?

**Comment by mkomko** [comment]
@volosied Would it be possible for you to take a stab at fixing this in the next weeks or months or should we think about a workaround? Thank you very much in advance for any information!

**Comment by volosied** [comment]
I can take another look at this.  I think my fix to assign ids to child elements is reasonable to address the duplicate id exception, and I don't see why the community would reject it.

**Comment by mkomko** [comment]
> I can take another look at this. I think my fix to assign ids to child elements is reasonable to address the duplicate id exception, and I don't see why the community would reject it.

That would be awesome, even more so if it also fixes https://issues.apache.org/jira/browse/MYFACES-4623 😅

**Comment by melloware** [comment]
Based on the analysis I am defensively never adding the scripts in the Restore phase on the Render phase as that is what Mojarra does.  I read Leo's email and his reasoning but to me it does not apply here so I am choosing to skip the Restore View phase.

**Comment by mkomko** [comment]
@melloware Hmm, so that fixes your case but not mine (https://issues.apache.org/jira/browse/MYFACES-4623) 😭 
@volosied Just so you know, thanks 😄

**Comment by melloware** [comment]
@mkomko yep they have a MyFaces fix going in for your issue.

**Comment by volosied** [comment]
@mkomko What JSF version do you need the fix in?

**Comment by melloware** [comment]
it is in PF 13.0.2 for both 2.3 and 4.0+ Jakarta

**Comment by melloware** [comment]
Oh sorry @volosied I think @mkomko is on JSF 4.0+

**Comment by mkomko** [comment]
@volosied Yep, 4.0+. Thanks guys!
