### ISSUE TITLE
MonacoEditor: Build Failing

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#683]
**Describe the bug**
The build is currently failing with this error... `Error: Non-zero exit code: 128 (git clone) (git://github.com/Microsoft/vscode-loc.git)`

```
C:\dev\primefaces\primefaces-extensions\monacoeditor\src\main\js>npm run generate-locales

> primefaces-extensions-resources-monacoeditor@1.0.0 generate-locales
> node generateLocales.js

C:\dev\primefaces\primefaces-extensions\monacoeditor\src\main\js\generateLocales.js:201
            if (err) throw err;
                     ^

Error: Non-zero exit code: 128 (git clone) (git://github.com/Microsoft/vscode-loc.git)
    at ChildProcess.<anonymous> (C:\dev\primefaces\primefaces-extensions\monacoeditor\src\main\js\node_modules\git-pull-or-clone\index.js:55:31)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (C:\dev\primefaces\primefaces-extensions\monacoeditor\src\main\js\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

cc @blutorange

**Comment by blutorange** [comment]
Hmm, seems to be broken in general, not be specific to a certain commit... let me see... (unless you've found why already?)
