### ISSUE TITLE
Sheet: Exception `org.primefaces.shaded.json.JSONException: JSONArray[0] is not a JSONArray` on events `columnSelect` and `rowSelect` 

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces-extensions/primefaces-extensions#722]
**Describe the bug**
I took a look at the sheet component. But a `JSONException` is thrown when a column or row is selected.

**Reproducer**
See showcase.

**To Reproduce**
1. Go to _Sheet -> Ajax events_ in the showcase.
2. Click on a column header or a row number.
3. See error:

```
Message: JSONArray[0] is not a JSONArray.
Timestamp: 2022-02-11 16:06:27
StackTrace: org.primefaces.shaded.json.JSONException: JSONArray[0] is not a JSONArray.
at org.primefaces.shaded.json.JSONArray.wrongValueFormatException(JSONArray.java:1692)
at org.primefaces.shaded.json.JSONArray.getJSONArray(JSONArray.java:463)
at org.primefaces.extensions.component.sheet.SheetRenderer.decodeSelection(SheetRenderer.java:844)
at org.primefaces.extensions.component.sheet.SheetRenderer.decode(SheetRenderer.java:744)
at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:479)
at javax.faces.component.UIInput.decode(UIInput.java:371)
at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1408)
at javax.faces.component.UIInput.processDecodes(UIInput.java:207)
at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:775)
at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1019)
at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
at javax.faces.component.UIForm.visitTree(UIForm.java:308)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialExecute(PartialViewContextImpl.java:435)
at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:416)
at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:97)
at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
at javax.faces.component.UIViewRoot$ApplyRequestValuesPhaseProcessor.process(UIViewRoot.java:1854)
at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1738)
at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:942)
at org.apache.myfaces.lifecycle.ApplyRequestValuesExecutor.execute(ApplyRequestValuesExecutor.java:42)
at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1452)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:123)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:516)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
at java.lang.Thread.run(Thread.java:745)
```

**Expected behavior**
Events are fired without exception.

**Comment by ltlBeBoy** [comment]
Maybe because of #605?

**Comment by ltlBeBoy** [comment]
I took a closer look at the source. And indeed the problem occurs due to the changes in #605:

- Clicking a single cell calls `SheetRenderer#decodeSelection(...)` once with an array of arrays (e.g. [[0,4,0,4]] for the first row and fourth column).
- Clicking a header/row calls `SheetRenderer#decodeSelection(...)` **three times**! First with an array of arrays (e.g. [[0,4,999,4]] for the fourth column) followed by two arrays with integer values (e.g. [-1,4,-1,4] twice).

Here a quick bug fix that worked for me:
```
            final JSONArray array = new JSONArray(jsonSelection);
            if (array.get(0) instanceof JSONArray) {
                // data comes in array of arrays
                for (int i = 0; i < array.length(); i++) {
                    updateSheetSelection(sheet, array.getJSONArray(i));
                }
            } else {
                // data comes in: [ [row, col, oldValue, newValue] ... ] after column/row selection
                updateSheetSelection(sheet, array);
            }

    ...

    private void updateSheetSelection(final Sheet sheet, final JSONArray array) throws JSONException {
        // data comes in: [ [row, col, oldValue, newValue] ... ]
        sheet.setSelectedRow(array.getInt(0));
        sheet.setSelectedColumn(sheet.getMappedColumn(array.getInt(1)));
        sheet.setSelectedLastRow(array.getInt(2));
        sheet.setSelectedLastColumn(array.getInt(3));
    }
```

**Comment by melloware** [comment]
Awesome let me fix it.

**Comment by melloware** [comment]
Take a look at my commit, I made it like yours but double check.

**Comment by ltlBeBoy** [comment]
Yes, it works as expected.
You could also remove the comment at row 841 `// data comes in array of arrays`. Because it's not always an array of arrays if the selection is a column / row. But that is nitpicking... ;-)

**Comment by melloware** [comment]
11.0.2 is in Maven Central now. Thanks for the assist.
