### ISSUE TITLE
Error PrimeRequestContext.isHideResourceVersion()

### ISSUE THREAD

**Issue by KimGabrielsen** [primefaces-extensions/primefaces-extensions#977]
### Describe the bug

I've updated my stack from JEE 8 to Jakarta ee 10 and Payara 6.2022Alpha4.

Updated my primefaces from 11.0 to Primefaces 12.0 Jakarta and 
extensions from 11.0.6 to 12.0.0.

When i try to run my application i receive an error:

'boolean org.primefaces.context.PrimeRequestContext.isHideResourceVersion()'

if I downgrade extensions to 11.0.6 the application is running but some java calls does not execute.

stack trace:

`
java.lang.NoSuchMethodError: 'boolean org.primefaces.context.PrimeRequestContext.isHideResourceVersion()'
	at org.primefaces.extensions.application.PrimeFacesExtensionsResource.<init>(PrimeFacesExtensionsResource.java:46)
	at org.primefaces.extensions.application.PrimeFacesExtensionsResourceHandler.wrapResource(PrimeFacesExtensionsResourceHandler.java:69)
	at org.primefaces.extensions.application.PrimeFacesExtensionsResourceHandler.createResource(PrimeFacesExtensionsResourceHandler.java:56)
	at org.primefaces.renderkit.HeadRenderer.encodeCSS(HeadRenderer.java:156)
	at org.primefaces.renderkit.HeadRenderer.encodeBegin(HeadRenderer.java:102)
	at jakarta.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:531)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1432)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:162)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1569)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.primefaces.serenity.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)

`

### Reproducer

I'm using the Primefaces Serentty application as a basis for testing.

### Expected behavior

I would have expected the application to run as it did with extensions 11.0.6

### PrimeFaces Extensions version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0

**Comment by KimGabrielsen** [comment]
I solved this issue.
closing it.
